TSEL/telkomsel/protected/models/Bts.php
<?php

/**
 * This is the model class for table "{{bts}}".
 *
 * The followings are the available columns in table '{{bts}}':
 * @property integer $id
 * @property integer $type
 * @property string $name
 * @property string $description
 * @property string $bts_id
 * @property string $longitude
 * @property string $latitude
 * @property string $first_ip
 * @property string $first_user
 * @property string $first_update
 * @property string $last_ip
 * @property string $last_user
 * @property string $last_update
 * @property string $lac
 * @property integer $show_flag
 * @property string $loc_stat_ip
 * @property integer $flag_deleted
 * @property integer $id_loc_stat
 * @property string $gis_id
 * @property string $gis_name
 * @property string $gis_date
 * @property integer $sector_type
 */
class Bts extends CActiveRecord
{
	//public $cellname;
	/**
	 * Returns the static model of the specified AR class.
	 * @return Bts the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{bts}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			//array('bts_name', 'cekUnique'),
			array('cellname', 'cekUnique'),
			
			array('bts_name, bts_id, lac,cellname,site_id,longitude,latitude', 'required'),
			
			array('show_flag, flag_deleted, id_loc_stat, sector_type', 'numerical', 'integerOnly'=>true),
			array('bts_name, first_user, last_user', 'length', 'max'=>100),
			array('description', 'length', 'max'=>100),
			array('bts_id', 'length', 'max'=>10),
			array('first_ip, last_ip, lac', 'length', 'max'=>20),
			array('loc_stat_ip, gis_id, gis_name', 'length', 'max'=>30),
			array('longitude, latitude, first_update, last_update, gis_date', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, type, bts_name,cellname,site_id,site_type, description, bts_id, longitude, latitude, first_ip, first_user, first_update, last_ip, last_user, last_update, lac, show_flag, loc_stat_ip, flag_deleted, id_loc_stat, gis_id, gis_name, gis_date, sector_type', 'safe', 'on'=>'search'),
		);
	}

		
	public function cekUnique($attribute,$params)
	{
		$current = Bts::model()->findByAttributes(array('cellname'=>$this->cellname,'site_id'=>$this->site_id,'bts_id'=>$this->bts_id,'lac'=>$this->lac,'type'=>0));
		if($current != ""){
			if($current->flag_deleted != 1 && $current->id != $this->id)
			$this->addError('cellname'," '$this->cellname' has already been taken.");
			$this->addError('site_id'," '$this->site_id' has already been taken.");
			$this->addError('bts_id'," '$this->bts_id' has already been taken.");
			$this->addError('lac'," '$this->lac' has already been taken.");
		}
	}
	
	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'Lac'=>array(self::BELONGS_TO, 'Lac', 'lac')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'type' => 'Type',
			'bts_name' => 'Name',
			'cellname' => 'Cell Name',
			'description' => 'Description',
			'bts_id' => 'Bts',
			'longitude' => 'Longitude',
			'latitude' => 'Latitude',
			'first_ip' => 'First Ip',
			'first_user' => 'First User',
			'first_update' => 'First Update',
			'last_ip' => 'Last Ip',
			'last_user' => 'Last User',
			'last_update' => 'Last Update',
			'lac' => 'Lac',
			'show_flag' => 'Show Flag',
			'loc_stat_ip' => 'Loc Stat Ip',
			'flag_deleted' => 'Flag Deleted',
			'id_loc_stat' => 'Id Loc Stat',
			'gis_id' => 'Gis',
			'gis_name' => 'Gis Name',
			'gis_date' => 'Gis Date',
			'sector_type' => 'Sector Type',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->condition=' type = 0 and (flag_deleted IS NULL or flag_deleted <>:deleted)';
		$criteria->params=array(':deleted'=>1);	
		
		$criteria->compare('id',$this->id);
		$criteria->compare('type',$this->type);
		$criteria->compare('bts_name',$this->bts_name,true);
		$criteria->compare('cellname',$this->cellname,true);
		$criteria->compare('site_id',$this->site_id,true);
		$criteria->compare('site_type',$this->site_type,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('bts_id',$this->bts_id,true);
		$criteria->compare('longitude',$this->longitude,true);
		$criteria->compare('latitude',$this->latitude,true);
		$criteria->compare('first_ip',$this->first_ip,true);
		$criteria->compare('first_user',$this->first_user,true);
		$criteria->compare('first_update',$this->first_update,true);
		$criteria->compare('last_ip',$this->last_ip,true);
		$criteria->compare('last_user',$this->last_user,true);
		$criteria->compare('last_update',$this->last_update,true);
		$criteria->compare('lac',$this->lac,true);
		$criteria->compare('show_flag',$this->show_flag);
		$criteria->compare('loc_stat_ip',$this->loc_stat_ip,true);
		$criteria->compare('flag_deleted',$this->flag_deleted);
		$criteria->compare('id_loc_stat',$this->id_loc_stat);
		$criteria->compare('gis_id',$this->gis_id,true);
		$criteria->compare('gis_name',$this->gis_name,true);
		$criteria->compare('gis_date',$this->gis_date,true);
		$criteria->compare('sector_type',$this->sector_type);

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
			'pagination'=>array(
			'pageSize'=>Yii::app()->params['paging'],
			),
		));
	}
}

TSEL/telkomsel/protected/controllers/BtsController.php
<?php

class BtsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'rights', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Bts;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bts']))
		{
			$model->attributes=$_POST['Bts'];
			
			$modelTampung = Bts::model()->findAllByAttributes(array('cellname'=>$model->cellname,'site_id'=>$model->site_id,'bts_id'=>$model->bts_id,'lac'=>$model->lac,'flag_deleted'=>1,'type'=>0));
			foreach ($modelTampung as $modelTT){
				$modelCeks[$modelTT->lac][$modelTT->bts_id][$modelTT->cellname][$modelTT->site_id] = $modelTT->id;
			}
			//$modelLac = CHtml::listData(Lac::model()->findAll(),'id','lac_id');
			//$model->lac = $modelLac[$model->lac];
			if(!isset($modelCeks[$model->lac][$model->bts_id][$model->cellname][$model->site_id])){
				$model->type = 0;
				if($model->save()){
					Controller::afterCreate("Bts",$model->id);
					Controller::addberita("Create CI : Name : $model->bts_name , Bts Id : $model->bts_id");
					$this->redirect(array('view','id'=>$model->id));
				}
			}
			else
			{
				$modelU=$this->loadModelFlag($modelCeks[$model->lac][$model->bts_id][$model->cellname][$model->site_id]);
				$modelU->attributes=$_POST['Bts'];
				$modelU->flag_deleted = 0; 
				if($modelU->save()){
					Controller::afterCreate("Bts",$modelU->id);
					Controller::addberita("Create CI : Name : $model->bts_name , Bts Id : $model->bts_id");
					$this->redirect(array('view','id'=>$modelU->id));
				}
			
			}
		}
		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$modelOld = $this->loadModel($id);
		//$modelLac = CHtml::listData(Lac::model()->findAll(),'lac_id','id');
		//$model->lac = $modelLac[$model->lac];
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bts']))
		{
			$model->attributes=$_POST['Bts'];
			//$modelLac = CHtml::listData(Lac::model()->findAll(),'id','lac_id');
			//$model->lac = $modelLac[$model->lac];
			if($model->save()){
				Controller::afterUpdate("Bts",$model->id);
				Controller::addberita("Update CI : shortcode : $modelOld->bts_name -> $model->bts_name , Lac Id : $modelOld->bts_id -> $model->bts_id");
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			if(Controller::cekExist($id,"id_bts","BtsGroupDetail")){
				$model=$this->loadModel($id);
				Controller::beforeDelete('Bts',$id);
				Controller::deleted('Bts',$id);
				Controller::addberita("Delete CI : Name : $model->bts_name , Lac Id : $model->bts_id");
				
				// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
				if(!isset($_GET['ajax']))
					$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
			}
			else
			{
				Yii::app()->user->setFlash('error', "Data in Use!");
				$this->redirect(array('index'));
			}
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */


	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model=new Bts('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Bts']))
			$model->attributes=$_GET['Bts'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Bts::model()->findByPk((int)$id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	public function loadModelFlag($lac,$bts_id,$cellname,$site_id)
	{
			
		$model = Bts::model()->findAllByAttributes(array('cellname'=>$cellname,'site_id'=>$site_id,'bts_id'=>$bts_id,'lac'=>$lac,'type'=>0));
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
	
	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='bts-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

TSEL/telkomsel/protected/views/bts/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'bts-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	

	<div class="row">
		<?php echo $form->labelEx($model,'bts_name'); ?>
		<?php echo $form->textField($model,'bts_name',array('size'=>50,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'bts_name'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'cellname'); ?>
		<?php echo $form->textField($model,'cellname',array('size'=>50,'maxlength'=>50)); //,'readonly'=>$model->isNewRecord ? false:true ?>
		<?php echo $form->error($model,'cellname'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'site_id'); ?>
		<?php echo $form->textField($model,'site_id',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'site_id'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'site_type'); ?>
		<?php echo $form->dropDownList($model,'site_type',Yii::app()->params["site_type"],array('empty'=>'--Please Select One--')); ?>
		<?php echo $form->error($model,'site_type'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textField($model,'description',array('size'=>50,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'description'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'bts_id'); ?>
		<?php echo $form->textField($model,'bts_id',array('size'=>10,'maxlength'=>10)); ?>
		<?php echo $form->error($model,'bts_id'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'lac'); ?>
		<?php echo $form->dropDownList($model,'lac',CHtml::listData(Lac::model()->findAll(array('condition'=>'flag_deleted IS NULL or flag_deleted <> 1','order'=>'lac_name')), 'lac_id', 'lac_name'),array('empty'=>'--Please Select One--')); ?>
		<?php echo $form->error($model,'lac'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'longitude'); ?>
		<?php echo $form->textField($model,'longitude',array('size'=>20,'maxlength'=>20)); ?>
		<?php echo $form->error($model,'longitude'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'latitude'); ?>
		<?php echo $form->textField($model,'latitude',array('size'=>20,'maxlength'=>20)); ?>
		<?php echo $form->error($model,'latitude'); ?>
	</div>

	


	
	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

TSEL/telkomsel/protected/views/bts/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>


	<div class="row">
		<?php echo $form->label($model,'bts_name'); ?>
		<?php echo $form->textField($model,'bts_name',array('size'=>50,'maxlength'=>50)); ?>
	</div>
	
	<div class="row">
		<?php echo $form->label($model,'cellname'); ?>
		<?php echo $form->textField($model,'cellname',array('size'=>50,'maxlength'=>50)); ?>
	</div>
	
	<div class="row">
		<?php echo $form->label($model,'site_id'); ?>
		<?php echo $form->textField($model,'site_id',array('size'=>50,'maxlength'=>50)); ?>
	</div>
	
	<div class="row">
		<?php echo $form->label($model,'site_type'); ?>
		<?php echo $form->dropDownList($model,'site_type',Yii::app()->params["site_type"],array('empty'=>'--Empty--')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'description'); ?>
		<?php echo $form->textField($model,'description',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'bts_id'); ?>
		<?php echo $form->textField($model,'bts_id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'longitude'); ?>
		<?php echo $form->textField($model,'longitude',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'latitude'); ?>
		<?php echo $form->textField($model,'latitude',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	
	<div class="row">
		<?php echo $form->label($model,'lac'); ?>
		<?php echo $form->textField($model,'lac',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

TSEL/telkomsel/protected/views/bts/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('type')); ?>:</b>
	<?php echo CHtml::encode($data->type); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('bts_id')); ?>:</b>
	<?php echo CHtml::encode($data->bts_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('longitude')); ?>:</b>
	<?php echo CHtml::encode($data->longitude); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('latitude')); ?>:</b>
	<?php echo CHtml::encode($data->latitude); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('first_ip')); ?>:</b>
	<?php echo CHtml::encode($data->first_ip); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('first_user')); ?>:</b>
	<?php echo CHtml::encode($data->first_user); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('first_update')); ?>:</b>
	<?php echo CHtml::encode($data->first_update); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_ip')); ?>:</b>
	<?php echo CHtml::encode($data->last_ip); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_user')); ?>:</b>
	<?php echo CHtml::encode($data->last_user); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_update')); ?>:</b>
	<?php echo CHtml::encode($data->last_update); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('lac')); ?>:</b>
	<?php echo CHtml::encode($data->lac); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('show_flag')); ?>:</b>
	<?php echo CHtml::encode($data->show_flag); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('loc_stat_ip')); ?>:</b>
	<?php echo CHtml::encode($data->loc_stat_ip); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('flag_deleted')); ?>:</b>
	<?php echo CHtml::encode($data->flag_deleted); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('id_loc_stat')); ?>:</b>
	<?php echo CHtml::encode($data->id_loc_stat); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('gis_id')); ?>:</b>
	<?php echo CHtml::encode($data->gis_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('gis_name')); ?>:</b>
	<?php echo CHtml::encode($data->gis_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('gis_date')); ?>:</b>
	<?php echo CHtml::encode($data->gis_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('sector_type')); ?>:</b>
	<?php echo CHtml::encode($data->sector_type); ?>
	<br />

	*/ ?>

</div>

TSEL/telkomsel/protected/views/bts/admin.php
<?php
$this->breadcrumbs=array(
	'CI'=>array('index'),
	'Manage',
);



Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('bts-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<?php if(Yii::app()->user->hasFlash('error')): ?>
 
<div class="flash-success">
    <font color="#000000" size="+1" style="background-color: #D2FFFE;"><?php echo Yii::app()->user->getFlash('error'); ?></font>
</div>
 
<?php endif; ?>
<table width="<?php echo Yii::app()->params['widthTableMenu']; ?>"><tr><td><h1>CI Management</h1></td>
<td><div class="operatorRight"><?php  Controller::createMenu(array(
				   array('label'=>'New','link'=>'bts/create','img'=>'/images/new.png','id'=>'','conf'=>'')
					));  ?></div></td>
					</tr></table>



<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'bts-grid',
	'dataProvider'=>$model->search(),	
	'columns'=>array(
		array(
			'name'=>'bts_name',
			'type'=>'raw',
			'value'=>'CHtml::link($data->bts_name,array("bts/view","id"=>$data->id))',
		),
		'cellname',
		'site_id',
		array(
			'name'=>'site_type',
			'type'=>'raw',
			'value'=>'@Yii::app()->params["site_type"][$data->site_type]',
		),
		'description',
		'bts_id',
		'longitude',
		'latitude',
		'lac',
		/*
		'latitude',
		'first_ip',
		'first_user',
		'first_update',
		'last_ip',
		'last_user',
		'last_update',
		'lac',
		'show_flag',
		'loc_stat_ip',
		'flag_deleted',
		'id_loc_stat',
		'gis_id',
		'gis_name',
		'gis_date',
		'sector_type',
		*/
		array(
			'class'=>'CButtonColumn',
			'template'=>'{view}{update}{delete}',
		    'buttons'=>array
		    (
		        
		        'delete' => array
		        (
		        	'visible'=>'Controller::cekExist($data->id,"id_bts","BtsGroupDetail") ? true : false',
					
		        ),
		    ),
			'header'=>'Action',
			'deleteConfirmation'=>"js:'Are you sure you want to delete this item??\\n\\nName :' +
        $(this).parents('tr').children(':eq(0)').text() +
        '\\n\\nThis operation cannot be undone.\\nPress \"OK\" to delete, or \"Cancel\" to abort without deleting.\\n\\n'",
		),
	),
)); ?>
<div class="operatorLeft">
<?php  Controller::createMenu(array(
	   array('label'=>'New','link'=>'bts/create','img'=>'/images/new.png','id'=>'','conf'=>'')
		));  ?>
</div>

TSEL/telkomsel/protected/views/bts/create.php
<?php
$this->breadcrumbs=array(
	'CI'=>array('index'),
	'Create',
);


?>
<table width="<?php echo Yii::app()->params['widthTableMenu']; ?>"><tr><td><h1>Create CI</h1></td>
<td><div class="operatorRight"><?php  Controller::createMenu(array(
				   array('label'=>'List','link'=>'bts/index','img'=>'/images/list.png','id'=>'','conf'=>'')
					));  ?></div></td>
					</tr></table>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

<div class="operatorLeft"><?php  Controller::createMenu(array(
				   array('label'=>'List','link'=>'bts/index','img'=>'/images/list.png','id'=>'','conf'=>'')
					));  ?></div>

TSEL/telkomsel/protected/views/bts/index.php
<?php
$this->breadcrumbs=array(
	'Bts',
);

$this->menu=array(
	array('label'=>'Create Bts', 'url'=>array('create')),
	array('label'=>'Manage Bts', 'url'=>array('admin')),
);
?>

<h1>Bts</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

TSEL/telkomsel/protected/views/bts/update.php
<?php
$this->breadcrumbs=array(
	'CI'=>array('index'),
	$model->bts_name=>array('view','id'=>$model->id),
	'Update',
);


?>

<table width="<?php echo Yii::app()->params['widthTableMenu']; ?>"><tr><td><h1>Update CI #<?php echo $model->bts_name; ?></h1></td>
<td><div class="operatorRight"><?php  Controller::createMenu(array(
	   array('label'=>'View','link'=>'bts/view','img'=>'/images/view.png','id'=>$model->id,'conf'=>''),
	   array('label'=>'List','link'=>'bts/index','img'=>'/images/list.png','id'=>'','conf'=>''),
	   array('label'=>'New','link'=>'bts/create','img'=>'/images/new.png','id'=>'','conf'=>'')
		));  ?></div></td>
					</tr></table>
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

 <div class="operatorLeft"><?php  Controller::createMenu(array(
	array('label'=>'New','link'=>'bts/create','img'=>'/images/new.png','id'=>'','conf'=>''),
	   array('label'=>'View','link'=>'bts/view','img'=>'/images/view.png','id'=>$model->id,'conf'=>''),
	   array('label'=>'List','link'=>'bts/index','img'=>'/images/list.png','id'=>'','conf'=>'')
	  
		));  ?></div>